/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ACS
 */
public class Feedbackform extends javax.swing.JFrame {
 Connection con =null;
    /**
     * Creates new form Feedbackform
     **/
    public Feedbackform() {
        initComponents();
        con=(Connection) MyConnection.con();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        Question1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        satisfied = new javax.swing.JRadioButton();
        notsatisfied = new javax.swing.JRadioButton();
        Question2 = new javax.swing.JLabel();
        satisfied2 = new javax.swing.JRadioButton();
        notsatisfied2 = new javax.swing.JRadioButton();
        Question3 = new javax.swing.JLabel();
        yes1 = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();
        Ouestion4 = new javax.swing.JLabel();
        satisfied4 = new javax.swing.JRadioButton();
        notsatisfied4 = new javax.swing.JRadioButton();
        Question5 = new javax.swing.JLabel();
        yes5 = new javax.swing.JRadioButton();
        no5 = new javax.swing.JRadioButton();
        Question6 = new javax.swing.JLabel();
        supportive6 = new javax.swing.JRadioButton();
        unsupportive6 = new javax.swing.JRadioButton();
        Question7 = new javax.swing.JLabel();
        good = new javax.swing.JRadioButton();
        bad = new javax.swing.JRadioButton();
        Question8 = new javax.swing.JLabel();
        yes8 = new javax.swing.JRadioButton();
        no8 = new javax.swing.JRadioButton();
        Question9 = new javax.swing.JLabel();
        yes9 = new javax.swing.JRadioButton();
        no9 = new javax.swing.JRadioButton();
        Question10 = new javax.swing.JLabel();
        yes10 = new javax.swing.JRadioButton();
        no10 = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Question1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question1.setText("1. Are you satisfied with the teaching staff and their teaching Methods?");

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel1.setText("Student Feedback");

        buttonGroup11.add(satisfied);
        satisfied.setText("Satisfied");
        satisfied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisfiedActionPerformed(evt);
            }
        });

        buttonGroup11.add(notsatisfied);
        notsatisfied.setText("Not Satisfied");
        notsatisfied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notsatisfiedActionPerformed(evt);
            }
        });

        Question2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question2.setText("2.How satisfied are you with the facilities provide by the collage ?");

        buttonGroup12.add(satisfied2);
        satisfied2.setText("Satisfied");
        satisfied2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisfied2ActionPerformed(evt);
            }
        });

        buttonGroup12.add(notsatisfied2);
        notsatisfied2.setText("Not Satisfied");
        notsatisfied2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notsatisfied2ActionPerformed(evt);
            }
        });

        Question3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question3.setText("3.was it easy to obtain the necessary resourcses from the collage library ?");

        buttonGroup13.add(yes1);
        yes1.setText("Yes");
        yes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes1ActionPerformed(evt);
            }
        });

        buttonGroup13.add(no1);
        no1.setText("No");
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });

        Ouestion4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ouestion4.setText("4.do you feel it is easier to register for different courses within the collage ?");

        buttonGroup14.add(satisfied4);
        satisfied4.setText("very satisfied");

        buttonGroup14.add(notsatisfied4);
        notsatisfied4.setText("Dissatisfied");

        Question5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question5.setText("5.what are you satisfied cleanliness and variety of food items avaible in the canteen?");

        buttonGroup15.add(yes5);
        yes5.setText("Yes");

        buttonGroup15.add(no5);
        no5.setText("No");

        Question6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question6.setText("6.how suppoetive were the faculty members? ");

        buttonGroup16.add(supportive6);
        supportive6.setText("Supportive ");

        buttonGroup16.add(unsupportive6);
        unsupportive6.setText("UnSupportive");

        Question7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question7.setText("7.what do Think about the Hostel?");

        buttonGroup17.add(good);
        good.setText("Good facility");

        buttonGroup17.add(bad);
        bad.setText("Bad");
        bad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badActionPerformed(evt);
            }
        });

        Question8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question8.setText("8.Are you satisfied with teaching staff and their teaching practices? ");

        buttonGroup18.add(yes8);
        yes8.setText("Yes");

        buttonGroup18.add(no8);
        no8.setText("No");

        Question9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question9.setText("9. Do you Think your siblings or friends will be benefited by studying at this collage ?");

        buttonGroup19.add(yes9);
        yes9.setText("Yes");

        buttonGroup19.add(no9);
        no9.setText("No");
        no9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no9ActionPerformed(evt);
            }
        });

        Question10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Question10.setText("10.Will you recommend this collage to others ? ");

        buttonGroup20.add(yes10);
        yes10.setText("Yes");

        buttonGroup20.add(no10);
        no10.setText("No");
        no10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no10ActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        submit1.setText("Clear");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(satisfied, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notsatisfied, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(satisfied2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(notsatisfied2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yes1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Ouestion4, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(satisfied4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(notsatisfied4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(yes5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(no5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Question6, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(supportive6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unsupportive6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Question7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(good)
                        .addGap(18, 18, 18)
                        .addComponent(bad, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Question9, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yes9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(no9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Question8, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(yes8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(no8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Question10, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yes10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(no10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satisfied)
                    .addComponent(notsatisfied))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satisfied2)
                    .addComponent(notsatisfied2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yes1)
                    .addComponent(no1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(satisfied4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ouestion4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(notsatisfied4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yes5)
                    .addComponent(no5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supportive6)
                    .addComponent(unsupportive6))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(good)
                    .addComponent(Question7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yes8)
                            .addComponent(no8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Question9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yes9)
                            .addComponent(no9))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yes10)
                    .addComponent(no10))
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(339, 339, 339))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void satisfiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisfiedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satisfiedActionPerformed

    private void notsatisfiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notsatisfiedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notsatisfiedActionPerformed

    private void satisfied2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisfied2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satisfied2ActionPerformed

    private void notsatisfied2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notsatisfied2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notsatisfied2ActionPerformed

    private void yes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yes1ActionPerformed

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver"); //jdbc:mysql://localhost:3306/database_1
            con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/database_1","root","");
            //JOptionPane.showMessageDialog(null,"connected database");
            String sql ="INSERT INTO `feedback_form`(`Questions1`, `Questions2`, `Questions3`, `Questions4`, `Questions5`, `Questions6`, `Questions7`, `Questions8`, `Questions9`, `Questions10`) VALUES (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);

            String Question1 = null;
            if(satisfied.isSelected()){
                Question1=satisfied.getText();
            }
            if(notsatisfied.isSelected()){
                Question1=notsatisfied.getText();
            }
            pst.setString(1,Question1);

            String Question2 = null;
            if(satisfied2.isSelected()){
                Question2=satisfied2.getText();
            }
            if(notsatisfied2.isSelected())
            {
                Question2=notsatisfied2.getText();
            }
            pst.setString(2,Question2);

            String Question3 = null;
            if(yes1.isSelected()){
                Question3=yes1.getText();
            }
            if(no1.isSelected())
            {
                Question3=no1.getText();
            }
            pst.setString(3,Question3);

            String Question4 = null;
            if(satisfied4.isSelected()){
                Question4=satisfied4.getText();
            }
            if(notsatisfied4.isSelected()){
                Question4=notsatisfied4.getText();
            }
            pst.setString(4,Question4);

            String Question5 = null;
            if(yes5.isSelected()){
                Question5=yes5.getText();
            }
            if(no5.isSelected()){
                Question5=no5.getText();
            }
            pst.setString(5,Question5);

            String Question6 = null;
            if(supportive6.isSelected()){
                Question6=supportive6.getText();
            }
            if(unsupportive6.isSelected())
            {
                Question6=unsupportive6.getText();
            }
            pst.setString(6,Question6);

            String Question7 = null;
            if(good.isSelected()){
                Question7=good.getText();
            }
            if(bad.isSelected())
            {
                Question7=bad.getText();
            }
            pst.setString(7,Question7);

            String Question8 = null;
            if(yes8.isSelected()){
                Question8=yes8.getText();
            }
            if(no8.isSelected())
            {
                Question8=no8.getText();
            }
            pst.setString(8,Question8);

            String Question9 = null;
            if(yes9.isSelected()){
                Question9=yes9.getText();
            }
            if(no9.isSelected())
            {
                Question9=no9.getText();
            }
            pst.setString(9,Question9);

            String Question10 = null;

            if(yes10.isSelected()){
                Question10=yes10.getText();
            }
            if(no10.isSelected())
            {
                Question10=no10.getText();
            }
            pst.setString(10,Question10);

            pst.executeUpdate();
            //pst.setString(5,jTextField5.getText());
            JOptionPane.showMessageDialog(null," Your feedback is Sucessful ");

            //dept.setText();
            // pst.setString(2,String.copyValueOf(jPasswordField1.getPassword()));

            // ResultSet rs=pst.executeQuery();
            //if(rs.next()){
                //JOptionPane.showMessageDialog(null,"Welcome "+jTextField1.getText(),"Sucessful Login",JOptionPane.PLAIN_MESSAGE);
                //new Student().setVisible(true);

                //}
            // else{
                //JOptionPane.showMessageDialog(null,"invalid user name/password","UnSucessful Login",JOptionPane.PLAIN_MESSAGE);
                //}
            con.close();
            dispose();
            // String username=MyConnection.jTextField1.getText();
        }

        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_submitActionPerformed

    private void no10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no10ActionPerformed

    private void badActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
         buttonGroup11.clearSelection();
          buttonGroup12.clearSelection();
           buttonGroup13.clearSelection();
            buttonGroup14.clearSelection();
             buttonGroup15.clearSelection();
              buttonGroup16.clearSelection();
               buttonGroup17.clearSelection();
                buttonGroup18.clearSelection();
                 buttonGroup19.clearSelection();
                  buttonGroup20.clearSelection();
                  
    }//GEN-LAST:event_submit1ActionPerformed

    private void no9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feedbackform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ouestion4;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question10;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question5;
    private javax.swing.JLabel Question6;
    private javax.swing.JLabel Question7;
    private javax.swing.JLabel Question8;
    private javax.swing.JLabel Question9;
    private javax.swing.JRadioButton bad;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.JRadioButton good;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton no1;
    private javax.swing.JRadioButton no10;
    private javax.swing.JRadioButton no5;
    private javax.swing.JRadioButton no8;
    private javax.swing.JRadioButton no9;
    private javax.swing.JRadioButton notsatisfied;
    private javax.swing.JRadioButton notsatisfied2;
    private javax.swing.JRadioButton notsatisfied4;
    private javax.swing.JRadioButton satisfied;
    private javax.swing.JRadioButton satisfied2;
    private javax.swing.JRadioButton satisfied4;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JRadioButton supportive6;
    private javax.swing.JRadioButton unsupportive6;
    private javax.swing.JRadioButton yes1;
    private javax.swing.JRadioButton yes10;
    private javax.swing.JRadioButton yes5;
    private javax.swing.JRadioButton yes8;
    private javax.swing.JRadioButton yes9;
    // End of variables declaration//GEN-END:variables
}
